title: unity-scene-gizmo
hero_image: images/banner.png
description: Use the scene gizmo to change the view
version: 1
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Use the scene gizmo to change the view
